name: my_practical
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_spinkit: ^5.2.1
  modal_progress_hud_nsn: ^0.5.1
  firebase_messaging: ^15.1.3
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  fluttertoast: ^8.2.8
  firebase_core:
  firebase_analytics:
  get_storage: ^2.1.1
  intl: ^0.19.0
  flutter_local_notifications: ^9.9.1
  permission_handler: ^11.0.1
  cloud_firestore:


  flutter: 
    sdk: flutter


dev_dependencies: 
#  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true

